config/routes.rb
Rails.application.routes.draw do
  get 'accounts/index'
  root 'accounts#index'

  resources :accounts do
  	collection do
  		get 	:get_balance
  		get 	:show_balance
  	end
  end
  resources :transactions
end

app/models/account.rb
class Account < ActiveRecord::Base
	#alidations
  validates :balance, presence: true

  #instance_methods
	def credit(amount)
		self.balance += amount
		self.save!
	end

	def debit(amount)
		self.balance -= amount
		self.save!
	end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  #Validations
  validates :source_account_id, presence: true
  validates :destination_account_id, presence: true
  validates :amount, presence: true
  validate  :check_if_accounts_exists
  validate  :check_if_destination_account_same_as_source_account
  validates_numericality_of :amount, greater_than: 0
  validates_numericality_of :amount, less_than_or_equal_to: :source_account_balance, if: lambda { |o| o.errors.empty? }


  #Hooks
  after_save :transfer_money

  def source_account_balance
    Account.find_by_id(self.source_account_id).balance
  end

  def check_if_destination_account_same_as_source_account
    errors.add(:destination_account_id, "Can't be the same as source account") if source_account_id == destination_account_id
  end

  def check_if_accounts_exists
    errors.add(:source_account_id, 'Account does not exist') if !Account.exists?(self.source_account_id)
    errors.add(:destination_account_id, 'Account does not exist') if !Account.exists?(self.destination_account_id)
  end

  def transfer_money
    source_account = Account.find(self.source_account_id)
    destination_account = Account.find(self.destination_account_id)
    source_account.debit(self.amount)
    destination_account.credit(self.amount)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  	@accounts = Account.all
  end

  def get_balance
  end

  def show_balance
  	@account = Account.find_by_id(params[:account][:id])
  	if @account.nil? 
  		flash[:alert] = 'Account does not exist'
  		render :get_balance
  	end
  end

  def show
  	@account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new()
  end

  def create
    prepare_params
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      redirect_to transaction_path(@transaction)
    else
      render :new
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end


  private

  def collection
    @transactions ||= end_of_association_chain.order('created_at').page(params[:page]).per(40)
  end

  def transaction_params
    params.require(:transaction).permit(:source_account_id, :destination_account_id, :amount)
  end

  protected
  def prepare_params
    params[:transaction][:amount].gsub!('R$ ', ' ')
    params[:transaction][:amount].gsub!('.', '')
    params[:transaction][:amount].gsub!(',', '.')
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/get_balance.html.slim
.col-lg-12
	.row.form-group
		- if flash[:alert]
			p.alert.alert-danger
				= flash[:alert]
	.row.form-group
		= simple_form_for :account, url: show_balance_accounts_path, method: :get do |f|
			.row.form-group
				= f.input :id, label: 'Account id', input_html: { value: "#{params[:account].try(:[], :id)}" }
			.row.form-group			
				= button_tag "Back", :type => 'button', :class => "pull-left btn btn-danger", :onclick => "location.href = '#{root_path()}'"
				= f.button :submit, "Get Balance", class: 'pull-right btn-success'

app/views/accounts/index.html.slim
.col-lg-12
  h1 Bank accounting

  .row.form-group
    .col-lg-12
      .btn-group.btn-group-justified aria-label="..." role="group"
        .btn-group role="group" 
          = link_to "Transfer Money", new_transaction_path, class: 'button btn btn-success'
        .btn-group role="group" 
          = link_to "Get Balance", get_balance_accounts_path, class: 'button btn btn-info'

  .row.form-group
    .col-md-4.col-md-offset-4
      - if @accounts.length == 0
        .alert.alert-info
          | Don't have accounts
      - else
        table.table.table-striped.table-bordered.table-hover
          thead
            tr
              th.center
                | Account id
              th.center
                | Saldo
          tbody
            - @accounts.each do |account|
              tr.center
                td
                  = account.id
                td
                  = number_to_currency(account.balance, unit: 'R$ ')

app/views/accounts/show_balance.html.slim
.col-lg-12
	h1 Balance
	.row.form-group
		.col-lg-12
			h3 Account #{@account.id}
			h4 = number_to_currency(@account.balance, unit: "R$ ")
	.row.form-group
		.col-lg-12
			= button_tag "Back", :type => 'button', :class => "btn btn-danger", :onclick => "location.href = '#{get_balance_accounts_path()}'"
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transfer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if params[:controller] == 'accounts' && params[:action] == 'index' %>
	<%= yield %>
<% else %>
	<div class="col-lg-6 col-lg-offset-3">
		<%= yield %>
	</div>
<% end %>

</body>
</html>

app/views/transactions/_form.html.slim
= simple_form_for(transaction) do |f|
  = f.input :source_account_id
  = f.input :destination_account_id
  = f.input :amount, as: :string, input_html: { class: 'js-mask-money' }
  = button_tag "Back", :type => 'button', :class => "pull-left btn btn-danger", :onclick => "location.href = '#{root_path()}'"
  = f.button :submit, "Transfer", class: 'pull-right btn-success'

javascript:
	$( document ).ready(function() {
	  $(".js-mask-money").maskMoney({prefix: 'R$ ', allowNegative: false, allowZero: true, defaultZero: true, thousands: '.', decimal: ',' , affixesStay : true});
	});

app/views/transactions/new.html.slim
.col-lg-12
	h1 Transfer Money
	= render :partial => "transactions/form", locals: {transaction: @transaction}

app/views/transactions/show.html.slim
.col-lg-12
	h1 Transaction
	.row.form-group
		.col-lg-5.text-right
			p
				| Account #{@transaction.source_account_id}:
				.text-danger 
					| - #{number_to_currency(@transaction.amount, unit: "R$ ")} 
		.col-lg-2.text-center
			.i.glyphicon.glyphicon-transfer.fa-4x
		.col-lg-5.text-left
			p
				| Account #{@transaction.destination_account_id}:
				.text-success 
					| + #{number_to_currency(@transaction.amount, unit: "R$ ")} 
	.row.form-group
		.col-lg-12
			= button_tag "Back", :type => 'button', :class => "pull-left btn btn-danger", :onclick => "location.href = '#{root_path()}'"
			= button_tag "New Transaction", :type => 'button', :class => "pull-right btn btn-success", :onclick => "location.href = '#{get_balance_accounts_path()}'"